### ISSUE TITLE
Output-от да оди на stdout наместо да запишува во фајл

### ISSUE THREAD

**Issue by lubeskih** [skopjehacklab/sentence-collector#8]
Output-от на програмата којшто сега се запишува во фајл, да оди на `stdout`, за да можеме на пример:

```cat hamlet.txt | python extractor.py | xclip -selection clipboard```
или
```cat hamlet.txt | python extractor.py > output.txt```

**Comment by MatejMecka** [comment]
Дали ќе имплементираме некаква проверка од корисникот за дали сака да е зачуван во датотека или цела логика на снимање во датотека ќе се отфрли за директно да се испечати на `stdout`?

**Comment by lubeskih** [comment]
> Дали ќе имплементираме некаква проверка од корисникот за дали сака да е зачуван во датотека или цела логика на снимање во датотека ќе се отфрли за директно да се испечати на `stdout`?

Да, најубаво е да ја отфрлиме и сѐ да иде на stdout:

1. Помалце код
2. Имаш слобода дали сакаш да го запишеш аутпутот во фајл или да го пајпаш на друго место

И со ова исто ќе се тргне и она "found n valid sentences ..." за аутпутот да биде чисто валидни реченици.

Му даваш текст -> ти вади реченици на stdout -> го пајпаш во xclip -> го пастираш на мозила -> мозила ќе ти каже колку реченици имаш.
